export enum ENUM_Column_type {
  GROUND_TRUTH = 'GROUND_TRUTH',
  GROUND_TRUTH_STATUS = 'GROUND_TRUTH_STATUS',
  IDENTIFIER = 'IDENTIFIER',
  PREDICTIVE_LABEL = 'PREDICTIVE_LABEL',
  INPUT = 'INPUT',
}

export enum ENUM_Data_type {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
}

export enum ENUM_Ground_truth_status {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
}

export enum ENUM_User_action {
  DATASET_UPLOADED = 'DATASET_UPLOADED',
  DATASET_DOWNLOADED = 'DATASET_DOWNLOADED',
  COLUMN_MARKED = 'COLUMN_MARKED',
  ROW_MARKED = 'ROW_MARKED',
  DATASET_RENAMED = 'DATASET_RENAMED',
  DATASET_DELETED = 'DATASET_DELETED',
  COLUMN_DELETED = 'COLUMN_DELETED',
}
