create type "public"."ENUM_Column_type" as enum ('GROUND_TRUTH', 'PREDICTIVE_LABEL', 'INPUT');

create type "public"."ENUM_Data_type" as enum ('STRING', 'NUMBER', 'DATE');

create type "public"."ENUM_Row_status" as enum ('PENDING', 'APPROVED');

create type "public"."ENUM_User_action" as enum ('DATASET_UPLOADED', 'DATASET_DOWNLOADED', 'COLUMN_MARKED', 'ROW_MARKED', 'DATASET_RENAMED', 'DATASET_DELETED', 'COLUMN_DELETED');

create table "public"."Dataset" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "file_name" text not null,
    "file_location" text not null,
    "file_type" text not null,
    "file_size" numeric not null,
    "total_rows" numeric not null,
    "deleted_at" timestamp with time zone
);


alter table "public"."Dataset" enable row level security;

create table "public"."Dataset_column" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dataset_id" bigint not null,
    "name" text not null,
    "dataType" "ENUM_Data_type" not null,
    "position" numeric,
    "type" "ENUM_Column_type" not null,
    "deleted_at" timestamp with time zone
);


alter table "public"."Dataset_column" enable row level security;

create table "public"."Dataset_row" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dataset_id" bigint not null,
    "position" numeric,
    "status" "ENUM_Row_status" not null
);


alter table "public"."Dataset_row" enable row level security;

create table "public"."Log_user_action" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "action" "ENUM_User_action" not null
);


alter table "public"."Log_user_action" enable row level security;

CREATE UNIQUE INDEX "Dataset_column_pkey" ON public."Dataset_column" USING btree (id);

CREATE UNIQUE INDEX "Dataset_pkey" ON public."Dataset" USING btree (id);

CREATE UNIQUE INDEX "Dataset_row_pkey" ON public."Dataset_row" USING btree (id);

CREATE UNIQUE INDEX "Log_user_action_pkey" ON public."Log_user_action" USING btree (id);

alter table "public"."Dataset" add constraint "Dataset_pkey" PRIMARY KEY using index "Dataset_pkey";

alter table "public"."Dataset_column" add constraint "Dataset_column_pkey" PRIMARY KEY using index "Dataset_column_pkey";

alter table "public"."Dataset_row" add constraint "Dataset_row_pkey" PRIMARY KEY using index "Dataset_row_pkey";

alter table "public"."Log_user_action" add constraint "Log_user_action_pkey" PRIMARY KEY using index "Log_user_action_pkey";

alter table "public"."Dataset_column" add constraint "Dataset_column_dataset_id_fkey" FOREIGN KEY (dataset_id) REFERENCES "Dataset"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Dataset_column" validate constraint "Dataset_column_dataset_id_fkey";

alter table "public"."Dataset_row" add constraint "Dataset_row_dataset_id_fkey" FOREIGN KEY (dataset_id) REFERENCES "Dataset"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Dataset_row" validate constraint "Dataset_row_dataset_id_fkey";


